### ISSUE TITLE
PyPI release of 0.3.1 

### ISSUE THREAD

**Issue by ZipBrandon** [fopina/django-bulk-update-or-create#39]
I've been using 0.3.1 from the tag here.  Is there a release coming to PyPI of it?  Thank you!

**Comment by fopina** [comment]
Thanks for bringing this up! I removed it from pypi after publishing (I think the issue I found led to #37)

I'll remove the release here from github as well so it doesn't confuse anyone.

The commits to `develop` branch are still pushed to pypi however but as pre-release packages

https://pypi.org/project/django-bulk-update-or-create/#history

So if you are using it as a generator (which is the one that works in this 0.3.1, the other does not), you can install `1.0.0.dev11` from pypi instead of github
